### ISSUE TITLE
 Upstream error: ISO host sent data with no client connected! Ignoring..

### ISSUE THREAD

**Issue by shoaibjdev** [juks/SocketQueue#13]
Hi,

What could be the reason for this error?

Have modified **smartVista.js** as per our service specs and able to get request formatted and succesfully sent to the server. But the response though it's correctly begin logged on the console gives below error.

 **Upstream error: ISO host sent data with no client connected! Ignoring..**

I used **nc** for testing and the above error is returned.
 cat custom_1200_a2a.txt - | nc 0.0.0.0 2014

**Comment by juks** [comment]
Hi,

Why 0.0.0.0? This message means your nc connection was closed before the actual response received.

**Comment by shoaibjdev** [comment]
Have just masked the IP here, am actually sending it to the server where SocketQueue is running.

**Comment by shoaibjdev** [comment]
**Update**: Have tried to curl on the HTTP Port and the response is same. Is there something I'm missing here? Curl repsonse is {"result":"","errors":["Gateway timeout"]}

But on Gateway (SocketQueue) response is as below for the curl:

2017-06-27 14:47:31 - info: Upstream error: ISO host sent data with no client connected! Ignoring...

ISO host says
================================================================================================

     [ <faulty>]

     Message Type Indicator [0].......................1210
     Bitmap [1].......................................F23005418AE080000000000004000000
     Primary Account Number [2].......................1140463000
     Processing Code [3]..............................400201
     Amount, Transaction [4]..........................50100
     Transmission Date and Time [7]...................20172706104904
     System Trace Audit Number [11]...................104904
     Time, Local Transaction [12].....................20172706104904
     Pos Entry Mode [22]..............................BANK3
     Function Code [24]...............................200
     Card acceptor business code [26].................5999
     Acquiring Institution Ident Code [32]............940400
     Forwarding institution identification code [33]..BANK63
     Retrieval Reference Number [37]..................2E5BD7BFB48B
     Response code [39]...............................93


===============================================================================================

**Comment by juks** [comment]
This means the syntax you use in your file is different from the one you implemented.

Does your remote system responds this message?

**Comment by shoaibjdev** [comment]
yes remote service is correctly responding, and log **ISO host says** is actually correct. There is no fault in the response being received and mapped by SocketQueue. Only i'm not able to receiving response at the curl and it's saying as above Upstream error: ISO host sent data with no client connected! Ignoring..

**Comment by juks** [comment]
Could you please provide the entire message body?

**Comment by shoaibjdev** [comment]
Below is link to complete request/response:
https://gist.github.com/shoaibjdev/ebd608e57da5da0923f5bcd489d39fdd

**Comment by juks** [comment]
I got it. The reason is your system deals with terminal ID that can contain strings (MOB00002). Need some time to improve.

**Comment by shoaibjdev** [comment]
Great! No issues, as you get time you could improve and release the patch. 
Meanwhile, i'll test another integration for ISO. Thank you so much for your time on this.

**Comment by juks** [comment]
Please pull the master and give it a try.

**Comment by shoaibjdev** [comment]
Hello Juks,

Issue re-occurred and not sure which field is causing it now, please advise.

Logs https://gist.github.com/shoaibjdev/15ffea75e4bedb29512a4dfc53b74cc8
