### ISSUE TITLE
Auto-reverse bug.

### ISSUE THREAD

**Issue by AlexKonstantinov** [juks/SocketQueue#17]
There is a case when SQ is hang up and can't take payments from terminals, that have sticked packages. The way to reproduce this bug is:
1) Send a purchase package, after that package is sent, sender should drop connection to make the IsoLogic to work.
2) First package generated by IsoLogic should retrieve faulty message code from IsoHost emulator, to relaunch it again.
3) The second package generated by IsoLogic should receive no response from IsoHost emulator, then SQ will try to delete that package from queue, but SQ won't be able to do that, so this package will stick in queue, and any other request made by this TerminalID won't proceed.

**Comment by juks** [comment]
Hello, Alex!

Thanks for digging deep. Need to find some time to reproduce the test case then fix. Will be back.

**Comment by juks** [comment]
Done
