### ISSUE TITLE
STAN or RRN in queue with tid

### ISSUE THREAD

**Issue by temper5** [juks/SocketQueue#22]
Hi, Igor.
Can you add parameter to define what field (STAN or RRN) use with tid for determinate transaction in queue.
I have work with processing that use field37 in request messages and in that case SocketQueue fail with error "Upstream error: ISO host sent data with no client connected! Ignoring..."
Example:

[iso_message.txt](https://github.com/juks/SocketQueue/files/1631540/iso_message.txt)
[1100_bal.txt](https://github.com/juks/SocketQueue/files/1630712/1100_bal.txt)

**Comment by juks** [comment]
Hi!

This is the second mention for nearly the same thing within one week: https://github.com/juks/SocketQueue/issues/21.

Means I will handle it soon :-)

**Comment by temper5** [comment]
Thank you. Everything is ok. Close the issue.

P.S. in issue comment you have mistake about 44=TID, but in code parameters.js you write correct 41=TID

**Comment by juks** [comment]
Updated the comment. Thanks!
