### ISSUE TITLE
Auto Reversal OpenWay

### ISSUE THREAD

**Issue by rustamin** [juks/SocketQueue#23]
Does auto reversal already implemented in OpenWay?
I see in `logic/openWay.js` some todo staff about implementing auto-reversal.

**Comment by juks** [comment]
Hi. It is not implemented at the moment, so everyone familiar with that is invited to contribute.

**Comment by rustamin** [comment]
Hallo @juks,

Can I confirm that to do auto reversal, basically I have to repack the data, then transmit it using `this.upstream.sendData(this, p);`?

**Comment by juks** [comment]
Yes, basically 200 message turns into 400 message with some fields changed. You may see an example here: https://github.com/juks/SocketQueue/blob/2f7b6519fce1c615be84ffdd672dae8cdbb35878/lib/iso8583/lib/logic/smartVista.js#L36

**Comment by rustamin** [comment]
Ok. Thanks, it's really helpful.
