### ISSUE TITLE
Use for iso8583 version 93

### ISSUE THREAD

**Issue by noecodjo** [juks/SocketQueue#24]
Hi Igor,
SQ is very useful
I have a question, because I want to use SQ to send a message to a version of the host ISO 8583 93.
I mean on this kind of version of ISO8583 the message type is in the form of 12XX or 18XX or 18XX
I created my own packager in but without much change in lib/iso8583/lib/packager...
Kindly assist

**Comment by juks** [comment]
Hi!

I am kind of very busy at the moment. So the only clue I can give is to grep the source for the appearance of 0200, 0800 and implement a solution of your own.

Yes, this should be replaced by some flexible logic one day.

**Comment by noecodjo** [comment]
hi Igor 
thanks for your reply
Can i get the function who test the MTI before process ? i mean a kind of function who manage accept MTi type in SQ

**Comment by juks** [comment]
Hi. The main MTI-related thing is located here: https://github.com/juks/SocketQueue/blob/master/lib/iso8583-packet/lib/iso8583Packet.js

**Comment by noecodjo** [comment]
Hi @juks 
Thanks for your feedback.
I'll take a look and revert if necessary

**Comment by mjallday** [comment]
This looks like a duplicate of #7
