### ISSUE TITLE
Start with config file reference error

### ISSUE THREAD

**Issue by kahwooi** [juks/SocketQueue#4]
Created a config:
```
{
    "upstreamHost":    "10.0.0.1",
    "upstreamPort":    5000,
    "listenPort":      2014,
    "vv":              true,
    "logFile":         "log.txt"
}
```

When I start, I got this error on Windows and Linux machine:

```
$ node socketQueue.js --c=config.json
C:\SocketQueue\socketQueue.js:46
    var val = readCfgParam(name, cfgData[name]);
              ^

ReferenceError: readCfgParam is not defined
    at Object.<anonymous> (C:\SocketQueue\socketQueue.js:46:15)

    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by juks** [comment]
This got broken after a recent code refactoring. Fixed! Please pull.

Thanks!

**Comment by juks** [comment]
Any more feedback?

**Comment by kahwooi** [comment]
This issue is fixed. Now I am having some problem understanding how to create a remote system configuration.  SocketQueue is currently supporting SmartVista / OpenWay processing systems. I guess my country banks are not using those processing systems. Do I just have to create my own custom.js.dist, or any other places I need to change?

**Comment by juks** [comment]
You can make your changes in any of bundled templates, renamed after the name of an exact system configuration you need to work with.

You may find and example of how folks from Mexico deal with this sort of work for PROSA system: https://github.com/lentiummmx/SocketQueue/tree/master/lib/iso8583/lib/packager

**Comment by juks** [comment]
Also, if you provide the real use cases, payloads of the system you need to communicate with, then you may count on me to make a new templates or implement some new configuration options.
