### ISSUE TITLE
http request gateway timeout

### ISSUE THREAD

**Issue by noecodjo** [juks/SocketQueue#45]
Hi igor,
I get an issue with http server.
When i sent request from http sclient to SQ, i get gateway timeout.
Below SQ log. My Host respond well , SQ get the response correctly but http client never get feedback

![image](https://user-images.githubusercontent.com/12713142/67489483-2c7a8b80-f661-11e9-9893-ab648de417b1.png)

Kindly assist

**Comment by juks** [comment]
Looks like you have found the answer? Is it premature connection close by on the client side?

**Comment by noecodjo** [comment]
yes ofcourse
After debug at my end i see that the issue comes from my logic. Cause i made some custom in the upstream module.
Thanks my dear
