### ISSUE TITLE
Custom Header & Support For EBCDIC format

### ISSUE THREAD

**Issue by indper** [juks/SocketQueue#6]
Hi Igor,

I want to know how to custom header value. For Example: Header length (bytes) and option for message length includes header length.

Also is it possible to send and receive ISO8583 using EBCDIC format.?

Thanks

**Comment by juks** [comment]
Hi!

There are two options that control the use of headers:
- useLengthHeader: adds message length header
- useStaticHeader=header adds a static header to each message

Regarding the EBCDIC, could you please provide the actual use cases (sample messages)? What kind of EBCDIC notation is used?

**Comment by indper** [comment]
Hi..

I am using Cardlink for host with EBCDIC format support. So I want to generate ISO8583 message with EBCIDIC format.

Thanks

**Comment by juks** [comment]
Cool, but could you provide the actual specification or examples of the messages you need to send?

EBCDIC is a kind of outdated character encoding system. That's okay. But if you just encode some sort of ISO-8583 format into EBCDIC, you will get no guarantee it will be understood by the remote system.

**Comment by juks** [comment]
Closed due to no response
