### ISSUE TITLE
iso8583/93 support

### ISSUE THREAD

**Issue by badlee** [juks/SocketQueue#7]
Hi,

How implement the iso8583-2:1993 Protocol with this solution?

Regards.

**Comment by juks** [comment]
Hi!

Basically this should be the same idea as maintaining a custom implementation of ISO System. It can be based on e.g. https://github.com/juks/SocketQueue/blob/master/lib/iso8583/lib/packager/smartVista.js setup.

- You can copy the settings file into a new custom config of your own
- Edit the data elements format according to your system configuration
- Run the service with the --hostConfig=your_system_name option

As far as I understand the MTI will be 1xxx. Not sure if it can cause some problems in the current implementation, But if you paste some examples, that can make things easier to understand.

**Comment by shoaibjdev** [comment]
Have tested with iso8583:1993 and it works by just modifying smartVista.js to adhere to 93 specs. MTI 1200, Response code (Field 39) to be 3 N etc. It simple and straight forward.

**Comment by badlee** [comment]
@shoaibjdev, thank you. Can you post your work?

**Comment by noecodjo** [comment]
Hi ,
somebody test with iso8583:1993? with message type 1XXX with response 1X10?
